### ISSUE TITLE
Gem::ConflictError: jruby-jars-9.1.14.0 conflicts with jruby-jars (~> 1.7.4)

### ISSUE THREAD

**Issue by jm3** [ianhattendorf/autocomplete-ruby#43]
Is there a known fix for this error when using Atom autocomplete-ruby? I tried uninstalling one or both jruby-jars gems and re-installing rsense, but it hasn't made a difference. The two jruby-jar names that rsense says conflict are both installed *by* rsense itself. In the autocomplete-ruby Atom settings, I tried both `/usr/local/bin/rsense` and `/Users/me/.rvm/rubies/ruby-2.4.2/bin/ruby` paths.

**Comment by ianhattendorf** [comment]
This seems to be an rsense issue. Are you able to try a clean install of ruby? I was able to install Atom, rsense, and autocomplete-ruby on my computer (Fedora 27) without error.

**Comment by ianhattendorf** [comment]
On second look, my install isn't working either. First error was regarding a missing require `rack/commonlogger`. After installing the `rack-commonlogger` gem, I'm getting logging errors regarding syntax errors in some of the dependent gems. It might be time to lay this plugin to rest, after 3 years of no rsense updates.

**Comment by jm3** [comment]
That makes sense. Maybe an ignorant question on my part, but why does a
Ruby autocomplete plugin need Java & jruby anyway? Would it be possible to
do something similar in ruby, and drop those requirements?

**Comment by ianhattendorf** [comment]
That's a good question. This plugin is basically just a wrapper of rsense (developed by someone else, see the link in the readme) which requires Java. It's been a few years since any development has happened with it, so this plugin is essentially just on life support. I believe VS Code has a few good plugins for Ruby (such as solargraph) if you aren't too tied in to Atom. A few might actually have been ported over to Atom.

**Comment by jm3** [comment]
ok, cool. i don't have the stomach for wading into the java fun-house so i'll just quietly close this. i know everyone loves VS Code but i'm not sure i'm ready to go there yet :) thanks for giving me the additional context.
